### ISSUE TITLE
Store address lat & lon either in term meta or in a transient

### ISSUE THREAD

**Issue by csalzano** [fridaysystems/inventory-presser#83]
- [x] Decide what the meta_keys will be
- [x] Change the Map widget to populate the values after getting them from openstreetmap.org
- [x] Change the Map widget to use stored values instead of crawling them every time
